/** @jsxImportSource preact */
import type { JSX } from "preact";
import { getIconData, iconToSVG, replaceIDs } from "@iconify/utils";
import type { AstroIconCollectionMap } from "../../typings/integration";
import type { AstroIconImport } from "../../typings/astro-icon-import";

// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import collections_mod from "virtual:astro-iconset";

const _collections = ((collections_mod as any).default ?? collections_mod) as AstroIconCollectionMap;

type BaseProps = Omit<JSX.SVGAttributes<SVGSVGElement>, "name"> & {
  size?: number | string;
  title?: string;
  desc?: string;
};

type IconProps =
  | (BaseProps & { name: IconName; icon?: never })
  | (BaseProps & { icon: AstroIconImport; name?: never });

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export default function Icon(props: IconProps) {
  const { name, icon, size, width, height, title, desc, ...rest } = props;
  const resolvedWidth = width ?? size;
  const resolvedHeight = height ?? size;

  let body: string;
  let svgAttrs: Record<string, string | undefined>;

  if (icon) {
    const renderData = iconToSVG(icon);
    body = replaceIDs(renderData.body);
    svgAttrs = {
      ...(renderData.attributes as Record<string, string>),
      ...(resolvedWidth != null ? { width: String(resolvedWidth) } : {}),
      ...(resolvedHeight != null ? { height: String(resolvedHeight) } : {}),
    };
  } else {
    const iconName = name as string;
    const colonIdx = iconName.indexOf(":");
    const setName = colonIdx === -1 ? "local" : iconName.slice(0, colonIdx);
    const iconKey = colonIdx === -1 ? iconName : iconName.slice(colonIdx + 1);

    const collection = _collections[setName];
    if (!collection)
      throw new Error(`[astro-iconset/preact] Icon set "${setName}" not found. Available: ${Object.keys(_collections).join(", ")}`);

    const iconData = getIconData(collection, iconKey);
    if (!iconData)
      throw new Error(`[astro-iconset/preact] Icon "${iconKey}" not found in set "${setName}".`);

    const renderData = iconToSVG(iconData);
    body = replaceIDs(renderData.body);
    svgAttrs = {
      ...(renderData.attributes as Record<string, string>),
      ...(resolvedWidth != null ? { width: String(resolvedWidth) } : {}),
      ...(resolvedHeight != null ? { height: String(resolvedHeight) } : {}),
    };
  }

  return (
    <svg
      {...(svgAttrs as JSX.SVGAttributes<SVGSVGElement>)}
      {...rest}
      data-icon={icon ? undefined : (name as string)}
      dangerouslySetInnerHTML={{
        __html:
          (title ? `<title>${escapeHtml(title)}</title>` : "") +
          (desc ? `<desc>${escapeHtml(desc)}</desc>` : "") +
          body,
      }}
    />
  );
}
