/** @jsxImportSource preact */
import type { JSX } from "preact";
import type { AstroIconImport } from "../../typings/astro-icon-import";
// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import { resolveIcon } from "../shared/core";

type BaseProps = Omit<JSX.IntrinsicElements["svg"], "name"> & {
  size?: number | string;
  title?: string;
  desc?: string;
};

type IconProps =
  | (BaseProps & { name: IconName; icon?: never })
  | (BaseProps & { icon: AstroIconImport; name?: never });

export default function Icon(props: IconProps) {
  const { name, icon, size, width, height, title, desc, ...rest } = props;
  const { attrs, inner, dataAttr } = resolveIcon(
    { name: name as string | undefined, icon, size, width: width as number | string | undefined, height: height as number | string | undefined, title, desc },
    "preact"
  );

  return (
    <svg
      {...(attrs as JSX.IntrinsicElements["svg"])}
      {...rest}
      {...(dataAttr
        ? { [dataAttr.name]: dataAttr.value }
        : {})}
      dangerouslySetInnerHTML={{ __html: inner }}
    />
  );
}
