<script setup lang="ts">
import { computed, watchEffect } from "vue";
import { getIconData, iconToSVG, replaceIDs } from "@iconify/utils";
import type { AstroIconCollectionMap } from "../../typings/integration";
import type { AstroIconImport } from "../../typings/astro-icon-import";
// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import collections_mod from "virtual:astro-iconset";

const _collections = ((collections_mod as any).default ?? collections_mod) as AstroIconCollectionMap;

const props = defineProps<{
  name?: IconName;
  icon?: AstroIconImport;
  size?: number | string;
  width?: number | string;
  height?: number | string;
  title?: string;
  desc?: string;
}>();

function escapeHtml(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

if (import.meta.env.DEV) {
  watchEffect(() => {
    if (props.size != null && (props.width != null || props.height != null)) {
      console.warn('[astro-iconset] Use either "size" or "width"/"height", not both. "width"/"height" takes priority.');
    }
  });
}

const rendered = computed(() => {
  if (props.icon != null && props.name != null) {
    throw new Error('[astro-iconset] Use either "name" or "icon", not both.');
  }

  const resolvedWidth = props.width ?? props.size;
  const resolvedHeight = props.height ?? props.size;

  let body: string;
  let attrs: Record<string, string> = {};

  if (props.icon) {
    const renderData = iconToSVG(props.icon);
    body = replaceIDs(renderData.body);
    attrs = { ...(renderData.attributes as Record<string, string>) };
  } else {
    const iconName = props.name as string;
    const colonIdx = iconName.indexOf(":");
    const setName = colonIdx === -1 ? "local" : iconName.slice(0, colonIdx);
    const iconKey = colonIdx === -1 ? iconName : iconName.slice(colonIdx + 1);

    const collection = _collections[setName];
    if (!collection)
      throw new Error(`[astro-iconset/vue] Icon set "${setName}" not found. Available: ${Object.keys(_collections).join(", ")}`);

    const iconData = getIconData(collection, iconKey);
    if (!iconData)
      throw new Error(`[astro-iconset/vue] Icon "${iconKey}" not found in set "${setName}".`);

    const renderData = iconToSVG(iconData);
    body = replaceIDs(renderData.body);
    attrs = { ...(renderData.attributes as Record<string, string>) };
  }

  if (resolvedWidth != null) attrs.width = String(resolvedWidth);
  if (resolvedHeight != null) attrs.height = String(resolvedHeight);

  const inner =
    (props.title ? `<title>${escapeHtml(props.title)}</title>` : "") +
    (props.desc ? `<desc>${escapeHtml(props.desc)}</desc>` : "") +
    body;

  return { attrs, inner };
});
</script>

<template>
  <svg
    v-bind="rendered.attrs"
    :data-icon="props.icon ? 'astro-iconset:import' : (props.name as string)"
    v-html="rendered.inner"
  />
</template>
