<script setup lang="ts">
import { computed } from "vue";
import type { AstroIconImport } from "../../typings/astro-icon-import";
// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import { resolveIcon } from "../shared/core";

const props = defineProps<{
  name?: IconName;
  icon?: AstroIconImport;
  size?: number | string;
  width?: number | string;
  height?: number | string;
  title?: string;
  desc?: string;
}>();

const rendered = computed(() =>
  resolveIcon(
    { name: props.name as string | undefined, icon: props.icon, size: props.size, width: props.width, height: props.height, title: props.title, desc: props.desc },
    "vue"
  )
);

const svgAttrs = computed(() => ({
  ...rendered.value.attrs,
  ...(rendered.value.dataAttr
    ? {
        [rendered.value.dataAttr.name]:
          rendered.value.dataAttr.value,
      }
    : {}),
}));
</script>

<template>
  <svg
    v-bind="svgAttrs"
    v-html="rendered.inner"
  />
</template>
