<script lang="ts">
  import { getIconData, iconToSVG, replaceIDs } from "@iconify/utils";
  import type { AstroIconCollectionMap } from "../../typings/integration";
  import type { AstroIconImport } from "../../typings/astro-icon-import";
  // @ts-ignore generated by typegen
  import type { Icon as IconName } from "virtual:astro-iconset";
  // @ts-ignore virtual module provided by astro-iconset vite plugin
  import collections_mod from "virtual:astro-iconset";

  const _collections = ((collections_mod as any).default ?? collections_mod) as AstroIconCollectionMap;

  export let name: IconName | undefined = undefined;
  export let icon: AstroIconImport | undefined = undefined;
  export let size: number | string | undefined = undefined;
  export let width: number | string | undefined = undefined;
  export let height: number | string | undefined = undefined;
  export let title: string | undefined = undefined;
  export let desc: string | undefined = undefined;

  function escapeHtml(s: string) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }

  $: resolvedWidth = width ?? size;
  $: resolvedHeight = height ?? size;

  $: result = (() => {
    let body: string;
    let attrs: Record<string, string> = {};

    if (icon) {
      const renderData = iconToSVG(icon);
      body = replaceIDs(renderData.body);
      attrs = { ...(renderData.attributes as Record<string, string>) };
    } else {
      const iconName = name as string;
      const colonIdx = iconName.indexOf(":");
      const setName = colonIdx === -1 ? "local" : iconName.slice(0, colonIdx);
      const iconKey = colonIdx === -1 ? iconName : iconName.slice(colonIdx + 1);

      const collection = _collections[setName];
      if (!collection)
        throw new Error(`[astro-iconset/svelte] Icon set "${setName}" not found. Available: ${Object.keys(_collections).join(", ")}`);

      const iconData = getIconData(collection, iconKey);
      if (!iconData)
        throw new Error(`[astro-iconset/svelte] Icon "${iconKey}" not found in set "${setName}".`);

      const renderData = iconToSVG(iconData);
      body = replaceIDs(renderData.body);
      attrs = { ...(renderData.attributes as Record<string, string>) };
    }

    if (resolvedWidth != null) attrs.width = String(resolvedWidth);
    if (resolvedHeight != null) attrs.height = String(resolvedHeight);

    const inner =
      (title ? `<title>${escapeHtml(title)}</title>` : "") +
      (desc ? `<desc>${escapeHtml(desc)}</desc>` : "") +
      body;

    return { attrs, inner };
  })();
</script>

<svg {...result.attrs} data-icon={icon ? undefined : name}>
  <!-- eslint-disable-next-line svelte/no-at-html-tags -->
  {@html result.inner}
</svg>
