<script lang="ts">
  import type { AstroIconImport } from "../../typings/astro-icon-import";
  // @ts-ignore generated by typegen
  import type { Icon as IconName } from "virtual:astro-iconset";
  import { resolveIcon } from "../shared/core";

  export let name: IconName | undefined = undefined;
  export let icon: AstroIconImport | undefined = undefined;
  export let size: number | string | undefined = undefined;
  export let width: number | string | undefined = undefined;
  export let height: number | string | undefined = undefined;
  export let title: string | undefined = undefined;
  export let desc: string | undefined = undefined;

  $: resolved = resolveIcon({ name: name as string | undefined, icon, size, width, height, title, desc }, "svelte");
</script>

<svg {...resolved.attrs} data-icon={resolved.dataIcon}>
  <!-- eslint-disable-next-line svelte/no-at-html-tags -->
  {@html resolved.inner}
</svg>
