/** @jsxImportSource solid-js */
import type { JSX, Component } from "solid-js";
import { splitProps } from "solid-js";
import type { AstroIconImport } from "../../typings/astro-icon-import";
// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import { resolveIcon } from "../shared/core";

type BaseProps = JSX.SvgSVGAttributes<SVGSVGElement> & {
  size?: number | string;
  title?: string;
  desc?: string;
};

type IconProps =
  | (BaseProps & { name: IconName; icon?: never })
  | (BaseProps & { icon: AstroIconImport; name?: never });

const Icon: Component<IconProps> = (rawProps) => {
  const [local, rest] = splitProps(rawProps, [
    "name", "icon", "size", "width", "height", "title", "desc",
  ]);

  const { attrs, inner, dataIcon } = resolveIcon(
    {
      name: local.name as string | undefined,
      icon: local.icon,
      size: local.size,
      width: local.width as number | string | undefined,
      height: local.height as number | string | undefined,
      title: local.title,
      desc: local.desc,
    },
    "solid"
  );

  return (
    <svg
      {...(attrs as JSX.SvgSVGAttributes<SVGSVGElement>)}
      {...rest}
      data-icon={dataIcon}
      innerHTML={inner}
    />
  );
};

export default Icon;
