/** @jsxImportSource solid-js */
import type { JSX, Component } from "solid-js";
import { splitProps } from "solid-js";
import { getIconData, iconToSVG, replaceIDs } from "@iconify/utils";
import type { AstroIconCollectionMap } from "../../typings/integration";
import type { AstroIconImport } from "../../typings/astro-icon-import";

// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import collections_mod from "virtual:astro-iconset";

const _collections = ((collections_mod as any).default ?? collections_mod) as AstroIconCollectionMap;

type BaseProps = JSX.SvgSVGAttributes<SVGSVGElement> & {
  size?: number | string;
  title?: string;
  desc?: string;
};

type IconProps =
  | (BaseProps & { name: IconName; icon?: never })
  | (BaseProps & { icon: AstroIconImport; name?: never });

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const Icon: Component<IconProps> = (rawProps) => {
  const [local, rest] = splitProps(rawProps, [
    "name", "icon", "size", "width", "height", "title", "desc",
  ]);

  const resolvedWidth = () => local.width ?? local.size;
  const resolvedHeight = () => local.height ?? local.size;

  const computed = () => {
    let body: string;
    let attrs: Record<string, string> = {};

    if (local.icon) {
      const renderData = iconToSVG(local.icon);
      body = replaceIDs(renderData.body);
      attrs = { ...(renderData.attributes as Record<string, string>) };
    } else {
      const iconName = local.name as string;
      const colonIdx = iconName.indexOf(":");
      const setName = colonIdx === -1 ? "local" : iconName.slice(0, colonIdx);
      const iconKey = colonIdx === -1 ? iconName : iconName.slice(colonIdx + 1);

      const collection = _collections[setName];
      if (!collection)
        throw new Error(`[astro-iconset/solid] Icon set "${setName}" not found. Available: ${Object.keys(_collections).join(", ")}`);

      const iconData = getIconData(collection, iconKey);
      if (!iconData)
        throw new Error(`[astro-iconset/solid] Icon "${iconKey}" not found in set "${setName}".`);

      const renderData = iconToSVG(iconData);
      body = replaceIDs(renderData.body);
      attrs = { ...(renderData.attributes as Record<string, string>) };
    }

    const w = resolvedWidth();
    const h = resolvedHeight();
    if (w != null) attrs.width = String(w);
    if (h != null) attrs.height = String(h);

    const inner =
      (local.title ? `<title>${escapeHtml(local.title)}</title>` : "") +
      (local.desc ? `<desc>${escapeHtml(local.desc)}</desc>` : "") +
      body;

    return { attrs, inner };
  };

  return (
    <svg
      {...(computed().attrs as JSX.SvgSVGAttributes<SVGSVGElement>)}
      {...rest}
      data-icon={local.icon ? undefined : (local.name as string)}
      innerHTML={computed().inner}
    />
  );
};

export default Icon;
